baseurl = "http://www.sfdcworkshop.com/"
languageCode = "en-us"
title = "Salesforce Developers 2017"
PygmentsCodeFences=true
pygmentsStyle="friendly"
googleAnalytics="UA-84811307-1"

[params]
  # Shown in the home page
  brand = "<div><img src='/workshop/2015sf_Developers_logo_RGB_KO.png' height='70'></div>"

[menu]
   

    [[menu.main]]
        name = "MINIHACKS"
        pre = "<i class='fa fa-list fa-fw'></i>"
        identifier = "minihacks"
        weight = 8
        url = "/minihacks/"
